### ISSUE TITLE
wsock32.dll not copying

### ISSUE THREAD

**Issue by Bobbyperson12** [RomeoCantCode/PSNorthstarWatcher#44] opened 2022-01-29 20:52 UTC
```
Given server directory destination does exist.
Titanfall2 source exists
Server directory C:\Users\Austi\AppData\Local\NorthstarServer\1 does not exists. creating
C:\Users\Austi\AppData\Local\NorthstarServer\1\R2Northstar does not exist. copying
C:\Users\Austi\AppData\Local\NorthstarServer\1\legal.txt does not exist. copying
C:\Users\Austi\AppData\Local\NorthstarServer\1\MinHook.x64.dll does not exist. copying
C:\Users\Austi\AppData\Local\NorthstarServer\1\Northstar.dll does not exist. copying
C:\Users\Austi\AppData\Local\NorthstarServer\1\NorthstarLauncher.exe does not exist. copying
C:\Users\Austi\AppData\Local\NorthstarServer\1\ns_startup_args.txt does not exist. copying
C:\Users\Austi\AppData\Local\NorthstarServer\1\ns_startup_args_dedi.txt does not exist. copying
C:\Users\Austi\AppData\Local\NorthstarServer\1\r2ds.bat does not exist. copying
Warning! Titanfall2 sources R2Northstar (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Warning! Titanfall2 sources legal.txt (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Warning! Titanfall2 sources MinHook.x64.dll (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Warning! Titanfall2 sources Northstar.dll (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Warning! Titanfall2 sources NorthstarLauncher.exe (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Warning! Titanfall2 sources ns_startup_args.txt (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Warning! Titanfall2 sources ns_startup_args_dedi.txt (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Warning! Titanfall2 sources r2ds.bat (file or folder of NorthStar)! Will try to exclude NS files and folders for symlinks.
Copying wsock32.dll to original TF2 folder to make things a bit easier
Error bulding servers!
Could not copy wsock32.dll
At line:1081 char:28
+                     catch {throw "Could not copy wsock32.dll"}
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not copy wsock32.dll:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not copy wsock32.dll

Copy-Item : Could not find a part of the path 'E:\SteamLibrary\steamapps\common\Titanfall2bin\x64_retail\'.
At line:1080 char:22
+ ...        try {Copy-Item ($($northstarpath.text) + "bin\x64_retail\wsock ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand

Could not copy wsock32.dll
At line:1081 char:28
+                     catch {throw "Could not copy wsock32.dll"}
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not copy wsock32.dll:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not copy wsock32.dll

Copy-Item : Could not find a part of the path 'E:\SteamLibrary\steamapps\common\Titanfall2bin\x64_retail\'.
At line:1080 char:22
+ ...        try {Copy-Item ($($northstarpath.text) + "bin\x64_retail\wsock ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand

Could not copy wsock32.dll
At line:1081 char:28
+                     catch {throw "Could not copy wsock32.dll"}
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not copy wsock32.dll:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not copy wsock32.dll

Copy-Item : Could not find a part of the path 'E:\SteamLibrary\steamapps\common\Titanfall2bin\x64_retail\'.
At line:1080 char:22
+ ...        try {Copy-Item ($($northstarpath.text) + "bin\x64_retail\wsock ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand


```

**Comment by RomeoCantCode** [comment] 2022-01-30 21:54
this should be fixed in latest commit / PR, but will test again

**Comment by RomeoCantCode** [comment] 2022-02-01 11:10
I tested this with the newest version, it is fixed. it was caused by a missing trailing backslash E:\SteamLibrary\steamapps\common\Titanfall2bin
should have been "Titanfall2\bin"
we should be able to release a stable 1.0 within the next weeks. mby doing another beta release in the mean time.

**Closed by RomeoCantCode** 2022-02-01 11:10 UTC
Labels: bug
